export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL';
export const FETCH_JOBS = 'FETCH_JOBS';
export const JOB_LIKED = 'JOB_LIKED';
export const JOB_LIKED_CLEAR = 'JOB_LIKED_CLEAR';
